# Generated by Django 6.0.6 on 2026-07-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('list', 'List / All'), ('django', 'Django'), ('python', 'Python'), ('code', 'Code / Web Dev'), ('briefcase', 'Career / Work'), ('lightbulb', 'Ideas / Thoughts'), ('database', 'Database'), ('api', 'API'), ('server', 'Server / Backend'), ('globe', 'Internet / Frontend'), ('lock', 'Security'), ('terminal', 'Terminal'), ('rocket', 'Deployment'), ('star', 'Featured'), ('heart', 'Favorites')], default='list', max_length=50),
        ),
    ]
